development:
  adapter: postgresql
  encoding: unicode
  database: dgs_development
  pool: 5
#  username: dgswebsite
#  password:
test:
  adapter: postgresql
  encoding: unicode
  database: dgswebsite_test
  pool: 5
  #username: dgswebsite
  #password:

production:
  adapter: postgresql
  encoding: unicode
  database: dgswebsite_production
  pool: 5
  #username: dgswebsite
  #password:
